class Config:
    MAX_THREADS = 500
    BEACON_PORT = 2010
    GATHER_WAIT_SEC = 30
    BUFFER_SIZE = 1024
    SF_API_VERSION = 9.0
    SF_API_TIMEOUT_SECS = 10
    SF_WAIT_FOR_API_SLEEP_SECS = 2
